# Weclome to the Sunday Lab!

# Lab Structure
- Post the materials on the Github before the Lab


- Review the asynchronous lecture on Wednesday


- Q&A time


- Stay at least 10 minutes 


- Update the notebook after the Lab if needed

# US Package
- https://github.com/unitedstates/python-us

# Groupby

In [19]:
from sklearn.datasets import load_boston
import pandas as pd
import numpy as np

In [20]:
boston_dataset = load_boston()
boston = pd.DataFrame(boston_dataset.data, columns=boston_dataset.feature_names)
boston.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33

- CRIM: Per capita crime rate by town
- ZN: Proportion of residential land zoned for lots over 25,000 sq. ft
- INDUS: Proportion of non-retail business acres per town
- CHAS: Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
- NOX: Nitric oxide concentration (parts per 10 million)
- RM: Average number of rooms per dwelling
- AGE: Proportion of owner-occupied units built prior to 1940
- DIS: Weighted distances to five Boston employment centers
- RAD: Index of accessibility to radial highways
- TAX: Full-value property tax rate per \$10,000
- PTRATIO: Pupil-teacher ratio by town
- B: 1000(Bk — 0.63)², where Bk is the proportion of [people of African American descent] by town
- LSTAT: Percentage of lower status of the population
- MEDV: Median value of owner-occupied homes in $1000s

In [21]:
def cat_crime_status(rate, low_status=False):
    if low_status:
        dummy = np.where(rate >= 11.360000, 'high', 'low')
        return dummy
    else:
        if rate <= 0.082045:
            return 'low'
        elif (rate > 0.082045) & (rate <= 3.677083):
            return 'medium'
        else:
            return 'high'
    
boston.loc[:, 'CRIM'] = boston.loc[:, 'CRIM'].map(cat_crime_status)
# The above method doesn't work in this case
# Error: boston.loc[:, 'LSTAT'] = boston.loc[:, 'CRIM'].map(cat_crime_status(low_status=True))
boston.loc[:, 'LSTAT'] = boston.loc[:, 'LSTAT'].map(lambda x:cat_crime_status(x, low_status=True))

In [22]:
print(boston.tail())

       CRIM   ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
501     low  0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0
502     low  0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0
503     low  0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0
504  medium  0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0
505     low  0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0

     PTRATIO       B LSTAT
501     21.0  391.99   low
502     21.0  396.90   low
503     21.0  396.90   low
504     21.0  393.45   low
505     21.0  396.90   low

In [24]:
boston_crime_status = boston.groupby(['CRIM','LSTAT'])
print(boston_crime_status.groups)
print(type(boston_crime_status.groups))

{('high', 'high'): [143, 356, 357, 358, 359, 361, 363, 366, 367, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 464, 466, ...], ('high', 'low'): [360, 362, 365, 368, 369, 370, 371, 372, 410, 463, 480, 481, 482], ('low', 'high'): [54, 78, 86, 120, 121, 185, 216, 286, 331, 346], ('low', 'low'): [0, 1, 2, 3, 4, 5, 35, 37, 39, 40, 51, 52, 53, 55, 56, 57, 64, 65, 66, 67, 74, 80, 81, 82, 83, 84, 85, 87, 88, 89, 90, 91, 92, 93, 94, 98, 99, 175, 176, 177, 178, 179, 180, 181, 186, 187, 191, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 217, 254, 255, 256, 274, 277, 278, 280, 281, 282, 283, 284, 285, 287, 288, 289, 290, 291, 292, 294, 296, 298, 299, 300, 301, 304, 305, 306, 307, 328, 329, 330, 332, 333, 334, 335, 336, 337, 338, 339, 340, ...], ('medium', 'high'): [6, 7, 8, 9, 10, 11, 12, 17, 18, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 36, 46, 47, 48, 49, 50, 60, 61, 68, 76, 103, 104, 105, 106, 107, 108, 109, 110, 112, 113, 115, 116, 118, 119, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 164, 167, 170, 171, 172, 184, 207, 208, 209, 210, 211, 212, 214, 218, 221, 230, 240, 241, 244, ...], ('medium', 'low'): [13, 14, 15, 16, 19, 38, 41, 42, 43, 44, 45, 58, 59, 62, 63, 69, 70, 71, 72, 73, 75, 77, 79, 95, 96, 97, 100, 101, 102, 111, 114, 117, 132, 157, 158, 159, 160, 161, 162, 163, 165, 166, 168, 169, 173, 174, 182, 183, 188, 189, 190, 192, 205, 206, 213, 215, 219, 220, 222, 223, 224, 225, 226, 227, 228, 229, 231, 232, 233, 234, 235, 236, 237, 238, 239, 242, 243, 246, 247, 248, 249, 250, 251, 252, 253, 257, 258, 259, 260, 261, 262, 263, 264, 265, 267, 268, 271, 272, 273, 275, ...]}
<class 'pandas.io.formats.printing.PrettyDict'>

In [11]:
print(boston_crime_status.count()/len(boston))
print(boston_crime_status.apply(lambda g: len(g)/len(boston)).round(2))

                    ZN     INDUS      CHAS       NOX        RM       AGE  \
CRIM   LSTAT
high   high   0.225296  0.225296  0.225296  0.225296  0.225296  0.225296
       low    0.025692  0.025692  0.025692  0.025692  0.025692  0.025692
low    high   0.019763  0.019763  0.019763  0.019763  0.019763  0.019763
       low    0.231225  0.231225  0.231225  0.231225  0.231225  0.231225
medium high   0.254941  0.254941  0.254941  0.254941  0.254941  0.254941
       low    0.243083  0.243083  0.243083  0.243083  0.243083  0.243083

                   DIS       RAD       TAX   PTRATIO         B
CRIM   LSTAT
high   high   0.225296  0.225296  0.225296  0.225296  0.225296
       low    0.025692  0.025692  0.025692  0.025692  0.025692
low    high   0.019763  0.019763  0.019763  0.019763  0.019763
       low    0.231225  0.231225  0.231225  0.231225  0.231225
medium high   0.254941  0.254941  0.254941  0.254941  0.254941
       low    0.243083  0.243083  0.243083  0.243083  0.243083
CRIM    LSTAT
high    high     0.23
        low      0.03
low     high     0.02
        low      0.23
medium  high     0.25
        low      0.24
dtype: float64

In [25]:
for key, item in boston_crime_status:
    print(item)

     CRIM   ZN  INDUS  CHAS    NOX     RM    AGE     DIS   RAD    TAX  \
143  high  0.0  19.58   0.0  0.871  5.468  100.0  1.4118   5.0  403.0
356  high  0.0  18.10   1.0  0.770  6.212   97.4  2.1222  24.0  666.0
357  high  0.0  18.10   1.0  0.770  6.395   91.0  2.5052  24.0  666.0
358  high  0.0  18.10   1.0  0.770  6.127   83.4  2.7227  24.0  666.0
359  high  0.0  18.10   0.0  0.770  6.112   81.3  2.5091  24.0  666.0
..    ...  ...    ...   ...    ...    ...    ...     ...   ...    ...
477  high  0.0  18.10   0.0  0.614  5.304   97.3  2.1007  24.0  666.0
478  high  0.0  18.10   0.0  0.614  6.185   96.7  2.1705  24.0  666.0
479  high  0.0  18.10   0.0  0.614  6.229   88.0  1.9512  24.0  666.0
486  high  0.0  18.10   0.0  0.583  6.114   79.8  3.5459  24.0  666.0
487  high  0.0  18.10   0.0  0.583  5.905   53.2  3.1523  24.0  666.0

     PTRATIO       B LSTAT
143     14.7  396.90  high
356     20.2  377.73  high
357     20.2  391.34  high
358     20.2  395.43  high
359     20.2  390.74  high
..       ...     ...   ...
477     20.2  349.48  high
478     20.2  379.70  high
479     20.2  383.32  high
486     20.2  392.68  high
487     20.2  388.22  high

[114 rows x 13 columns]
     CRIM   ZN  INDUS  CHAS    NOX     RM    AGE     DIS   RAD    TAX  \
360  high  0.0   18.1   0.0  0.770  6.398   88.0  2.5182  24.0  666.0
362  high  0.0   18.1   0.0  0.770  5.362   96.2  2.1036  24.0  666.0
365  high  0.0   18.1   0.0  0.718  3.561   87.9  1.6132  24.0  666.0
368  high  0.0   18.1   0.0  0.631  4.970  100.0  1.3325  24.0  666.0
369  high  0.0   18.1   1.0  0.631  6.683   96.8  1.3567  24.0  666.0
370  high  0.0   18.1   1.0  0.631  7.016   97.5  1.2024  24.0  666.0
371  high  0.0   18.1   0.0  0.631  6.216  100.0  1.1691  24.0  666.0
372  high  0.0   18.1   1.0  0.668  5.875   89.6  1.1296  24.0  666.0
410  high  0.0   18.1   0.0  0.597  5.757  100.0  1.4130  24.0  666.0
463  high  0.0   18.1   0.0  0.713  6.513   89.9  2.8016  24.0  666.0
480  high  0.0   18.1   0.0  0.532  6.242   64.7  3.4242  24.0  666.0
481  high  0.0   18.1   0.0  0.532  6.750   74.9  3.3317  24.0  666.0
482  high  0.0   18.1   0.0  0.532  7.061   77.0  3.4106  24.0  666.0

     PTRATIO       B LSTAT
360     20.2  374.56   low
362     20.2  380.79   low
365     20.2  354.70   low
368     20.2  375.52   low
369     20.2  375.33   low
370     20.2  392.05   low
371     20.2  366.15   low
372     20.2  347.88   low
410     20.2    2.60   low
463     20.2  393.82   low
480     20.2  396.90   low
481     20.2  393.07   low
482     20.2  395.28   low
    CRIM    ZN  INDUS  CHAS     NOX     RM   AGE     DIS  RAD    TAX  PTRATIO  \
54   low  75.0   4.00   0.0  0.4100  5.888  47.6  7.3197  3.0  469.0     21.1
78   low   0.0  12.83   0.0  0.4370  6.232  53.7  5.0141  5.0  398.0     18.7
86   low   0.0   4.49   0.0  0.4490  6.015  45.1  4.4272  3.0  247.0     18.5
120  low   0.0  25.65   0.0  0.5810  5.870  69.7  2.2577  2.0  188.0     19.1
121  low   0.0  25.65   0.0  0.5810  6.004  84.1  2.1974  2.0  188.0     19.1
185  low   0.0   2.46   0.0  0.4880  6.153  68.8  3.2797  3.0  193.0     17.8
216  low   0.0  13.89   1.0  0.5500  5.888  56.0  3.1121  5.0  276.0     16.4
286  low  80.0   1.76   0.0  0.3850  6.230  31.5  9.0892  1.0  241.0     18.2
331  low  35.0   6.06   0.0  0.4379  5.706  28.4  6.6407  1.0  304.0     16.9
346  low   0.0   4.39   0.0  0.4420  5.898  52.3  8.0136  3.0  352.0     18.8

          B LSTAT
54   396.90  high
78   386.40  high
86   395.99  high
120  389.15  high
121  377.67  high
185  387.11  high
216  392.80  high
286  341.60  high
331  394.02  high
346  364.61  high
    CRIM    ZN  INDUS  CHAS    NOX     RM   AGE      DIS  RAD    TAX  PTRATIO  \
0    low  18.0   2.31   0.0  0.538  6.575  65.2   4.0900  1.0  296.0     15.3
1    low   0.0   7.07   0.0  0.469  6.421  78.9   4.9671  2.0  242.0     17.8
2    low   0.0   7.07   0.0  0.469  7.185  61.1   4.9671  2.0  242.0     17.8
3    low   0.0   2.18   0.0  0.458  6.998  45.8   6.0622  3.0  222.0     18.7
4    low   0.0   2.18   0.0  0.458  7.147  54.2   6.0622  3.0  222.0     18.7
..   ...   ...    ...   ...    ...    ...   ...      ...  ...    ...      ...
354  low  80.0   1.91   0.0  0.413  5.663  21.9  10.5857  4.0  334.0     22.0
501  low   0.0  11.93   0.0  0.573  6.593  69.1   2.4786  1.0  273.0     21.0
502  low   0.0  11.93   0.0  0.573  6.120  76.7   2.2875  1.0  273.0     21.0
503  low   0.0  11.93   0.0  0.573  6.976  91.0   2.1675  1.0  273.0     21.0
505  low   0.0  11.93   0.0  0.573  6.030  80.8   2.5050  1.0  273.0     21.0

          B LSTAT
0    396.90   low
1    396.90   low
2    392.83   low
3    394.63   low
4    396.90   low
..      ...   ...
354  382.80   low
501  391.99   low
502  396.90   low
503  396.90   low
505  396.90   low

[117 rows x 13 columns]
       CRIM    ZN  INDUS  CHAS    NOX     RM    AGE     DIS  RAD    TAX  \
6    medium  12.5   7.87   0.0  0.524  6.012   66.6  5.5605  5.0  311.0
7    medium  12.5   7.87   0.0  0.524  6.172   96.1  5.9505  5.0  311.0
8    medium  12.5   7.87   0.0  0.524  5.631  100.0  6.0821  5.0  311.0
9    medium  12.5   7.87   0.0  0.524  6.004   85.9  6.5921  5.0  311.0
10   medium  12.5   7.87   0.0  0.524  6.377   94.3  6.3467  5.0  311.0
..      ...   ...    ...   ...    ...    ...    ...     ...  ...    ...
496  medium   0.0   9.69   0.0  0.585  5.390   72.9  2.7986  6.0  391.0
497  medium   0.0   9.69   0.0  0.585  5.794   70.6  2.8927  6.0  391.0
498  medium   0.0   9.69   0.0  0.585  6.019   65.3  2.4091  6.0  391.0
499  medium   0.0   9.69   0.0  0.585  5.569   73.5  2.3999  6.0  391.0
500  medium   0.0   9.69   0.0  0.585  6.027   79.7  2.4982  6.0  391.0

     PTRATIO       B LSTAT
6       15.2  395.60  high
7       15.2  396.90  high
8       15.2  386.63  high
9       15.2  386.71  high
10      15.2  392.52  high
..       ...     ...   ...
496     19.2  396.90  high
497     19.2  396.90  high
498     19.2  396.90  high
499     19.2  395.77  high
500     19.2  396.90  high

[129 rows x 13 columns]
       CRIM    ZN  INDUS  CHAS    NOX     RM   AGE      DIS   RAD    TAX  \
13   medium   0.0   8.14   0.0  0.538  5.949  61.8   4.7075   4.0  307.0
14   medium   0.0   8.14   0.0  0.538  6.096  84.5   4.4619   4.0  307.0
15   medium   0.0   8.14   0.0  0.538  5.834  56.5   4.4986   4.0  307.0
16   medium   0.0   8.14   0.0  0.538  5.935  29.3   4.4986   4.0  307.0
19   medium   0.0   8.14   0.0  0.538  5.727  69.5   3.7965   4.0  307.0
..      ...   ...    ...   ...    ...    ...   ...      ...   ...    ...
355  medium  80.0   1.91   0.0  0.413  5.936  19.5  10.5857   4.0  334.0
364  medium   0.0  18.10   1.0  0.718  8.780  82.9   1.9047  24.0  666.0
483  medium   0.0  18.10   0.0  0.532  5.762  40.3   4.0983  24.0  666.0
485  medium   0.0  18.10   0.0  0.583  6.312  51.9   3.9917  24.0  666.0
504  medium   0.0  11.93   0.0  0.573  6.794  89.3   2.3889   1.0  273.0

     PTRATIO       B LSTAT
13      21.0  396.90   low
14      21.0  380.02   low
15      21.0  395.62   low
16      21.0  386.85   low
19      21.0  390.95   low
..       ...     ...   ...
355     22.0  376.04   low
364     20.2  354.55   low
483     20.2  392.92   low
485     20.2  388.62   low
504     21.0  393.45   low

[123 rows x 13 columns]

In [28]:
sample_list = []
for key, item in boston_crime_status:
    # print(item)
    sample_list.append(item.iloc[0:2, :])
print(sample_list[0])

     CRIM   ZN  INDUS  CHAS    NOX     RM    AGE     DIS   RAD    TAX  \
143  high  0.0  19.58   0.0  0.871  5.468  100.0  1.4118   5.0  403.0
356  high  0.0  18.10   1.0  0.770  6.212   97.4  2.1222  24.0  666.0

     PTRATIO       B LSTAT
143     14.7  396.90  high
356     20.2  377.73  high

In [29]:
for item in sample_list[1:]:
    sample_list[0] = pd.concat([sample_list[0], item], join = 'inner') 
sample_df = sample_list[0]
print(sample_df)

       CRIM    ZN  INDUS  CHAS    NOX     RM    AGE     DIS   RAD    TAX  \
143    high   0.0  19.58   0.0  0.871  5.468  100.0  1.4118   5.0  403.0
356    high   0.0  18.10   1.0  0.770  6.212   97.4  2.1222  24.0  666.0
360    high   0.0  18.10   0.0  0.770  6.398   88.0  2.5182  24.0  666.0
362    high   0.0  18.10   0.0  0.770  5.362   96.2  2.1036  24.0  666.0
54      low  75.0   4.00   0.0  0.410  5.888   47.6  7.3197   3.0  469.0
78      low   0.0  12.83   0.0  0.437  6.232   53.7  5.0141   5.0  398.0
0       low  18.0   2.31   0.0  0.538  6.575   65.2  4.0900   1.0  296.0
1       low   0.0   7.07   0.0  0.469  6.421   78.9  4.9671   2.0  242.0
6    medium  12.5   7.87   0.0  0.524  6.012   66.6  5.5605   5.0  311.0
7    medium  12.5   7.87   0.0  0.524  6.172   96.1  5.9505   5.0  311.0
13   medium   0.0   8.14   0.0  0.538  5.949   61.8  4.7075   4.0  307.0
14   medium   0.0   8.14   0.0  0.538  6.096   84.5  4.4619   4.0  307.0

     PTRATIO       B LSTAT
143     14.7  396.90  high
356     20.2  377.73  high
360     20.2  374.56   low
362     20.2  380.79   low
54      21.1  396.90  high
78      18.7  386.40  high
0       15.3  396.90   low
1       17.8  396.90   low
6       15.2  395.60  high
7       15.2  396.90  high
13      21.0  396.90   low
14      21.0  380.02   low

# String Modification

In [30]:
sample_df['CRIM'] = sample_df['CRIM'].str.upper()
sample_df['LSTAT'] = sample_df['LSTAT'].str.upper()
print(sample_df.head())

     CRIM    ZN  INDUS  CHAS    NOX     RM    AGE     DIS   RAD    TAX  \
143  HIGH   0.0  19.58   0.0  0.871  5.468  100.0  1.4118   5.0  403.0
356  HIGH   0.0  18.10   1.0  0.770  6.212   97.4  2.1222  24.0  666.0
360  HIGH   0.0  18.10   0.0  0.770  6.398   88.0  2.5182  24.0  666.0
362  HIGH   0.0  18.10   0.0  0.770  5.362   96.2  2.1036  24.0  666.0
54    LOW  75.0   4.00   0.0  0.410  5.888   47.6  7.3197   3.0  469.0

     PTRATIO       B LSTAT
143     14.7  396.90  HIGH
356     20.2  377.73  HIGH
360     20.2  374.56   LOW
362     20.2  380.79   LOW
54      21.1  396.90  HIGH